# Generated by Django 4.1 on 2022-08-20 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blog_img',
            new_name='blog_image',
        ),
    ]
