# Generated by Django 4.0.6 on 2022-08-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Blog', '0002_rename_blog_img_blog_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, max_length=264, null=True, unique=True),
        ),
    ]
